[package]
name = "durl"
version = "1.0.0"
authors = ["yuya <yuyas203@gmail.com>"]
edition = "2018"

[dependencies]
url = "1.7"
failure = "0.1"
structopt = "0.2"
atty = "0.2"
log = "0.4"
pretty_env_logger = "0.2"